spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://mysql:3306/gym_notifications?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-group

server:
  port: 8091
